# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rDBpsKDOTyeyB3AoZ-f7acPyk8n8vznV
"""

pip install chatterbot

pip install chatterbot_corpus

import spacy

from spacy.cli.download import download

download(model="en_core_web_sm")

from chatterbot import ChatBot

from chatterbot.trainers import ListTrainer

chatbot = ChatBot("name")

trainer = ListTrainer(chatbot)

trainer.train(["Hi, can I help you?","Sure, I'd like to book your flight tickets to Iceland", "Your Flight tickets are booked"])

response = chatbot.get_response("Hi")

print(response)

while True:
  query = input()
  if query=='exit':
      break
  ans = chatbot.get_response(query)
  print("Bot:",ans )

